-- MySQL Script generated by MySQL Workbench
-- Fri Aug 23 15:14:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema T_VoteServerDB
-- -----------------------------------------------------
-- 投票服务组件数据库
DROP SCHEMA IF EXISTS `T_VoteServerDB` ;

-- -----------------------------------------------------
-- Schema T_VoteServerDB
--
-- 投票服务组件数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `T_VoteServerDB` DEFAULT CHARACTER SET utf8 ;
USE `T_VoteServerDB` ;

-- -----------------------------------------------------
-- Table `T_VoteServerDB`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_VoteServerDB`.`Users` ;

CREATE TABLE IF NOT EXISTS `T_VoteServerDB`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `uuid` CHAR(30) NOT NULL COMMENT '用户UUID',
  `name` VARCHAR(45) NULL COMMENT '用户名称',
  `email` VARCHAR(45) NOT NULL COMMENT '电子邮件',
  `password` VARCHAR(500) NULL COMMENT '密码',
  `status` VARCHAR(45) NULL COMMENT '状态',
  `createdAt` TIMESTAMP NULL COMMENT '创建时间',
  `modifiedAt` TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `T_VoteServerDB`.`VerificationCodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_VoteServerDB`.`VerificationCodes` ;

CREATE TABLE IF NOT EXISTS `T_VoteServerDB`.`VerificationCodes` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `uuid` CHAR(30) NOT NULL COMMENT '验证码资源UUID',
  `email` VARCHAR(45) NOT NULL COMMENT '邮件',
  `code` VARCHAR(45) NULL COMMENT '验证码',
  `expiredAt` TIMESTAMP NULL COMMENT '过期时间',
  `createdAt` TIMESTAMP NULL COMMENT '创建时间',
  `modifiedAt` TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
COMMENT = '邮件验证码表';


-- -----------------------------------------------------
-- Table `T_VoteServerDB`.`Candidates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_VoteServerDB`.`Candidates` ;

CREATE TABLE IF NOT EXISTS `T_VoteServerDB`.`Candidates` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `uuid` CHAR(30) NOT NULL COMMENT '候选人UUID',
  `name` VARCHAR(45) NOT NULL COMMENT '候选人名称',
  `description` VARCHAR(2000) NULL COMMENT '候选人简介或描述',
  `createdAt` TIMESTAMP NULL COMMENT '创建时间',
  `modifiedAt` TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC))
ENGINE = InnoDB
COMMENT = '候选人表';


-- -----------------------------------------------------
-- Table `T_VoteServerDB`.`Activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_VoteServerDB`.`Activities` ;

CREATE TABLE IF NOT EXISTS `T_VoteServerDB`.`Activities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(30) NOT NULL,
  `name` VARCHAR(100) NULL COMMENT '活动名称',
  `description` VARCHAR(2000) NULL COMMENT '活动相关描述',
  `startAt` TIMESTAMP NULL COMMENT '活动开始时间',
  `endAt` TIMESTAMP NULL COMMENT '活动结束时间',
  `status` VARCHAR(45) NULL COMMENT '状态',
  `createdAt` TIMESTAMP NULL COMMENT '创建时间',
  `modifiedAt` TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC))
ENGINE = InnoDB
COMMENT = '投票活动表';


-- -----------------------------------------------------
-- Table `T_VoteServerDB`.`CandidateActivitiesMemberships`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_VoteServerDB`.`CandidateActivitiesMemberships` ;

CREATE TABLE IF NOT EXISTS `T_VoteServerDB`.`CandidateActivitiesMemberships` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `uuid` CHAR(30) NOT NULL COMMENT '关系资源UUID',
  `activityUUID` CHAR(30) NOT NULL COMMENT '活动UUID',
  `candidateUUID` CHAR(30) NOT NULL COMMENT '候选人UUID',
  `createdAt` TIMESTAMP NULL COMMENT '创建时间',
  `modifiedAt` TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  INDEX `activityUUID_idx` (`activityUUID` ASC),
  INDEX `candidateUUID_idx` (`candidateUUID` ASC))
ENGINE = InnoDB
COMMENT = '候选人与活动关系表';


-- -----------------------------------------------------
-- Table `T_VoteServerDB`.`UserActivityRecords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_VoteServerDB`.`UserActivityRecords` ;

CREATE TABLE IF NOT EXISTS `T_VoteServerDB`.`UserActivityRecords` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `uuid` CHAR(30) NOT NULL COMMENT '投票记录UUID',
  `userUUID` CHAR(30) NULL COMMENT '用户UUID',
  `activityUUID` CHAR(30) NULL COMMENT '活动UUID',
  `createdAt` TIMESTAMP NULL COMMENT '创建时间',
  `modifiedAt` TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  INDEX `userUUID_idx` (`userUUID` ASC),
  UNIQUE INDEX `user_acitivity_uni` (`userUUID` ASC, `activityUUID` ASC),
  INDEX `activityUUID_idx` (`activityUUID` ASC))
ENGINE = InnoDB
COMMENT = '用户参与投票活动记录';


-- -----------------------------------------------------
-- Table `T_VoteServerDB`.`Votes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_VoteServerDB`.`Votes` ;

CREATE TABLE IF NOT EXISTS `T_VoteServerDB`.`Votes` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `uuid` CHAR(30) NOT NULL COMMENT '投票UUID',
  `userActivityRecordUUID` CHAR(30) NULL COMMENT '记录UUID',
  `activityUUID` CHAR(30) NOT NULL COMMENT '活动UUID',
  `candidateUUID` CHAR(30) NOT NULL COMMENT '候选人UUID',
  `userUUID` CHAR(30) NOT NULL COMMENT '用户UUID',
  `count` INT NULL COMMENT '票数',
  `createdAt` TIMESTAMP NULL COMMENT '创建时间',
  `modifiedAt` TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  INDEX `activityUUID_idx` (`activityUUID` ASC),
  INDEX `userUUID_idx` (`userUUID` ASC),
  INDEX `candidateUUID_idx` (`candidateUUID` ASC),
  INDEX `userActivityRecordUUID_idx` (`userActivityRecordUUID` ASC))
ENGINE = InnoDB
COMMENT = '投票统计表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
